# Generated by Django 4.0.5 on 2022-07-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_likes',
        ),
    ]
