# Generated by Django 4.0.5 on 2022-07-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_post_like_users_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_users',
        ),
    ]
