# Generated by Django 3.1.7 on 2022-04-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_auto_20220404_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='edittime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
