# Generated by Django 4.0.3 on 2022-04-10 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_post_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='duedate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
